#!/bin/bash

source utils

cd /tmp

printf "Fetching file ${AWS_S3_RESTORE_SQL_FILE}..."
s3cmd -c $work_dir/.s3cfg get ${AWS_S3_RESTORE_SQL_FILE} > /dev/null
printf "%s\n" "${green}OK${end}"

file="${AWS_S3_RESTORE_SQL_FILE##*/}"

if [[ $file =~ \.gz$ ]]; then
    printf "Looks to be gzipped - uncompressing..."
    gunzip $file || exit 1    
    file=${file%.*}
    printf "%s\n" "${green}OK${end}"
fi

if [ "$DROP_DB_IF_EXISTS" = true ]; then
printf "Dropping database ${MYSQL_DATABASE}..."
mysql -h${MYSQL_HOST} -u${MYSQL_USER} -p${MYSQL_PASSWORD} -e "DROP DATABASE IF EXISTS ${MYSQL_DATABASE}" >/dev/null || exit 1
printf "%s\n" "${green}OK${end}"
fi

printf "Creating database ${MYSQL_DATABASE}..."
mysql -h${MYSQL_HOST} -u${MYSQL_USER} -p${MYSQL_PASSWORD} -e "CREATE DATABASE ${MYSQL_DATABASE}" >/dev/null || exit 1
printf "%s\n" "${green}OK${end}"

printf "Restoring database ${MYSQL_DATABASE}..."
mysql -h${MYSQL_HOST} -u${MYSQL_USER} -p${MYSQL_PASSWORD} ${MYSQL_DATABASE} >/dev/null < ${file} || exit 1
printf "%s\n" "${green}OK${end}"


printf "Deleting downloaded restore file ${file}..."
rm $file
printf "%s\n" "${green}OK${end}"

printf "\n%s\n" "${blue}Done!${end}"
