#!/bin/bash

source settings

cd ${WORK_DIR}

printf "Fetching file ${S3_RESTORE_PATH}..."
s3cmd -c ${INSTALL_DIR}/.s3cfg get ${S3_RESTORE_PATH} > /dev/null
printf "%s\n" "${green}OK${end}"

file="${S3_RESTORE_PATH##*/}"

if [[ $file =~ \.gz$ ]]; then
    printf "Looks to be gzipped - uncompressing..."
    gunzip $file || exit 1    
    file=${file%.*}
    printf "%s\n" "${green}OK${end}"
fi

if [ "$DROP_DB_IF_EXISTS" = true ]; then
printf "Dropping database ${MYSQL_DATABASE}..."
mysql ${MYSQL_OPTS} -e "DROP DATABASE IF EXISTS ${MYSQL_DATABASE}" >/dev/null || exit 1
printf "%s\n" "${green}OK${end}"
fi

printf "Creating database ${MYSQL_DATABASE}..."
mysql ${MYSQL_OPTS} -e "CREATE DATABASE ${MYSQL_DATABASE}" >/dev/null || exit 1
printf "%s\n" "${green}OK${end}"

printf "Restoring database ${MYSQL_DATABASE}..."
mysql ${MYSQL_OPTS} ${MYSQL_DATABASE} >/dev/null < ${file} || exit 1
printf "%s\n" "${green}OK${end}"


printf "Deleting downloaded restore file ${file}..."
rm $file
printf "%s\n" "${green}OK${end}"

printf "\n%s\n" "${blue}Done!${end}"
